# Generated by Django 5.2.15 on 2026-07-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststatus',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
