# Generated by Django 5.2.15 on 2026-07-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_teststatus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststatus',
            name='subject',
            field=models.CharField(blank=True, choices=[('history', 'Tarix'), ('uzbek', 'Ona tili va adabiyot'), ('russian', 'Rus tili')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='teststatus',
            name='test_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
