# Generated by Django 5.2.15 on 2026-09-23 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RashResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_ball', models.FloatField(blank=True, null=True)),
                ('essay_ball', models.FloatField(blank=True, null=True)),
                ('rash_ball', models.FloatField(blank=True, null=True)),
                ('percent', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'rash_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('question_number', models.CharField(max_length=10)),
                ('correct_answer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='admin_panel.teststatus')),
            ],
        ),
    ]
