# Generated by Django 5.2.15 on 2026-07-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0003_alter_teststatus_subject_alter_teststatus_test_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('question_number', models.CharField(max_length=10)),
                ('correct_answer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='admin_panel.teststatus')),
            ],
        ),
    ]
