# Generated by Django 5.2.15 on 2026-07-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RashResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_ball', models.FloatField(blank=True, null=True)),
                ('essay_ball', models.FloatField(blank=True, null=True)),
                ('rash_ball', models.FloatField(blank=True, null=True)),
                ('percent', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'rash_results',
                'managed': False,
            },
        ),
    ]
